version: '3.8'
services:
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test_docker_db
      MYSQL_USER: test_docker_user
      MYSQL_PASSWORD: test_docker_pass
    ports:
      - 4306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
       PMA_HOST: database
  php: 
    container_name: php
    build: 
      context: ./php
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
    - 8080:80
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  